server:
  port: 8022

#  项目名称
spring:
  application:
    name: rabiit_consumer

  #    rabbitmq服务器配置
  rabbitmq:
    host: 8.136.41.79
    port: 5672
    username: admin
    password: admin
nacos:
  config:
    server-addr:

